name: chemsmart
channels:
  - conda-forge  # handles conda installations
  - defaults
dependencies:
  - python=3.10
  - pymol-open-source=3.1.0
  - pip
  - pip:
      - -e .[test]  # Pulls in pyproject.toml dependencies
